export default
[
  {
    title: 'Movies',
    imageSrc: './images/projects/project_card_4.png',
    tags: [
      'HTML',
      'Webpack',
      'CSS',
      'JavaScript',
    ],
    text: 'In this JavaScript capstone project we built a web application based on an external API. The webapp has 2 user interfaces:\n- A home page showing a list of items (movies) that you can "like."\n- A popup window with more data about an item that you can use to comment on it.',
    liveLink: null,
    sourceLink: 'https://github.com/akucintavalent/js-capstone',
  },
  {
    title: 'Space Travelers\' Hub',
    imageSrc: './images/projects/project_card_7.png',
    tags: [
      'React',
      'Redux',
      'JavaScript',
      'CSS',
      'HTML',
    ],
    text: 'This is a capstone project, it is working with the real live data from the SpaceX API. It is a web application for a company that provides commercial and scientific space travel services. The application will allow users to book rockets and join selected space missions.',
    liveLink: 'https://vigorous-darwin-db6969.netlify.app/',
    sourceLink: 'https://github.com/akucintavalent/space-travelers-hub',
  },
  {
    title: 'COVID-19 stats',
    imageSrc: './images/projects/project_card_8.png',
    tags: [
      'React',
      'Redux',
      'JavaScript',
      'CSS',
      'HTML',
    ],
    text: 'This is a capstone project, it is working with the real live data from the Narrativa API (COVID-19 data) and build a web application for a company that displays COVID-19 data for the previous day.',
    liveLink: 'https://keen-wright-b70cfc.netlify.app/',
    sourceLink: 'https://github.com/akucintavalent/covid-19-stats',
  },
  {
    title: 'Blog App',
    imageSrc: './images/projects/project_card_9.png',
    tags: [
      'Ruby on Rails',
      'CSS',
      'HTML',
      'PostgreSQL',
    ],
    text: 'The Blog app is a classic example of a blog website. It is a fully functional website that will show the list of posts and empower readers to interact with them by adding comments and liking posts.',
    liveLink: null,
    sourceLink: 'https://github.com/akucintavalent/blog',
  },
  {
    title: 'Recipe App',
    imageSrc: './images/projects/project_card_10.png',
    tags: [
      'Ruby on Rails',
      'CSS',
      'HTML',
      'PostgreSQL',
    ],
    text: 'The Recipe app keeps track of all the users\' recipes, ingredients, and inventory. It will allow the user to save ingredients, keep track of what they have, create recipes, and generate a shopping list based on what they have and what they are missing from a recipe. Also, since sharing recipes is an important part of cooking the app should allow the user to make them public so anyone can access them.',
    liveLink: null,
    sourceLink: 'https://github.com/Meri-MG/recipe-app',
  },
  {
    title: 'Car Booking Service',
    imageSrc: './images/projects/project_card_12.png',
    tags: [
      'Ruby on Rails',
      'React',
      'Redux',
      'CSS',
      'HTML',
      'PostgreSQL',
    ],
    text: 'Car Booking Service app is an app where registered users can book cars.',
    liveLink: 'https://deploy-preview-37--willowy-empanada-95e169.netlify.app/',
    sourceLink: 'https://github.com/DelhinRharl/car-booking-service-front-end',
  },
];